FROM ghcr.io/jgowdy/rust-slim-bullseye-cache AS slim-bullseye-cargo-index

COPY /cobhan /cobhan

WORKDIR /cobhan/library/rust/libcobhandemo

RUN cargo update

FROM ghcr.io/jgowdy/rust-slim-bullseye-cache AS libcobhandemo-build-bullseye-slim

COPY --from=slim-bullseye-cargo-index /usr/local/cargo /usr/local/cargo

