FROM ghcr.io/jgowdy/rust-alpine-cache AS alpine-cargo-index

ENV ALPINE=1

COPY /cobhan /cobhan/

WORKDIR /cobhan/library/rust/libcobhandemo

RUN cargo update

FROM ghcr.io/jgowdy/rust-alpine-cache AS libcobhan-build-alpine

RUN apk add build-base py3-cffi

COPY --from=alpine-cargo-index /usr/local/cargo /usr/local/cargo
