name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cobhan-rust-build:$(date +%s)
    - name: Publish the Docker image
      run: docker push cobhan-rust-build:latest
