name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile.bullseye --tag ghcr.io/jgowdy/cobhan-rust-bullseye:latest
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Publish the Docker image
      run: docker push ghcr.io/jgowdy/cobhan-rust-bullseye:latest
